version: "3"
services:
  # my-app:
  #   image: 309168474583.dkr.ecr.eu-north-1.amazonaws.com/my-app:1.0     //stopped this repository image on awsecr after checking
  #   ports:
  #     - 3000:3000
  mongodb-container:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-vol:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-container

volumes:
  mongo-vol:
    driver: local
